---

- name: "Manage custom mime types, if defined"
  become: true
  lineinfile: >-
    {{ item | combine({
      'dest': nginx_mime_path,
      'owner': 'root',
      'group': 'root',
      'mode': '0644',
      'insertbefore': '^}$'
      }) }}
  with_items: "{{ nginx_mime_extra | list }}"
  when: "nginx_mime_extra | length > 0"
  notify:
    - "reload nginx"


- name: "Manage nginx.conf"
  become: true
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_config_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "validate nginx config"
    - "reload nginx"


- name: "Manage upstream.conf"
  become: true
  template:
    src: "upstream.conf.j2"
    dest: "{{ nginx_vhost_dir }}/upstream.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "nginx_vhost_upstream | length > 0"
  notify:
    - "validate nginx config"
    - "reload nginx"


- name: "Remove upstream.conf, if not defined"
  become: true
  file:
    path: "{{ nginx_vhost_dir }}/upstream.conf"
    state: "absent"
  when: "nginx_vhost_upstream | length == 0"
  notify:
    - "validate nginx config"
    - "reload nginx"


- name: "Manage default.conf"
  become: true
  template:
    src: "default.conf.j2"
    dest: "{{ nginx_vhost_dir }}/default.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "nginx_vhost_default | length > 0"
  notify:
    - "validate nginx config"
    - "reload nginx"


- name: "Remove default.conf if not defined"
  become: true
  file:
    path: "{{ nginx_vhost_dir }}/default.conf"
    state: "absent"
  when: "nginx_vhost_default | length == 0"
  notify:
    - "validate nginx config"
    - "reload nginx"
