---

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags: ["nginx", "nginx-install", "nginx-configure", "nginx-service"]


- name: "Manage nginx package(s)"
  become: true
  package:
    name: "{{ nginx_packages | list }}"
    state: "{{ nginx_package_state }}"
  when: "nginx_install"
  tags: ["nginx", "nginx-install"]


- include_tasks: "configure.yml"
  when: "nginx_configure"
  tags: ["nginx", "nginx-configure"]


- name: "Manage nginx service"
  become: true
  service:
    name: "{{ nginx_service_name }}"
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
  when: "nginx_service"
  tags: ["nginx", "nginx-service"]
