---

- name: "Validate nginx config"
  become: true
  ansible.builtin.command: "nginx -t"


- name: "Reload nginx service"
  become: true
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    state: "reloaded"
  when:
    - "nginx_service"
    - "nginx_service_state == 'started'"
